#
# PHP Dependencies
#
FROM composer:1.9.3 as vendor

WORKDIR /app

COPY src/database/ database/
COPY src/composer.json composer.json
COPY src/composer.lock composer.lock

RUN composer install \
    --no-interaction \
    --no-plugins \
    --no-scripts \
    --no-dev \
    --prefer-dist

COPY ./src .
RUN composer dump-autoload

#
# Application
#
FROM php:7.4-fpm

WORKDIR /app

# Install PHP dependencies
RUN apt-get update -y && apt-get install -y libxml2-dev libonig-dev
RUN docker-php-ext-install pdo pdo_mysql mbstring opcache tokenizer xml ctype json bcmath pcntl

# Copy Composer dependencies
COPY --from=vendor /app/vendor/ ./vendor/
COPY ./src .

ENTRYPOINT php artisan redis:listen-repositories