version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: server
    volumes:
      - ./src:/var/www/html
      - ./config/nginx:/etc/nginx/conf.d:ro
    depends_on:
      - php
    network_mode: "host"

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    user: "${WORKSPACE_PUID}"
    volumes:
      - ./src:/var/www/html
      - ./config/php:/usr/local/etc/php-fpm.d:ro
    network_mode: "host"
