#!/usr/bin/env bash
docker run --rm -ti \
    --network ${NETWORK:-infraspeak-pie} \
    --user $(id -u):$(id -g) \
    --volume /etc/passwd:/etc/passwd:ro \
    --volume /etc/group:/etc/group:ro \
    --volume ~/.config/composer:/tmp \
    --volume $(pwd):/app \
    -w /app \
    infraspeak-pie/github-issue-finder-composer \
    composer $@
